---
version: "3.8"
services:
  movies:
    image: nileshkumar2343/paytm_movies:latest
    ports:
      - 61:80
    deploy:
      replicas: 3
  train:
    image: nileshkumar2343/paytm_train:latest
    ports:
      - 62:80
    deploy:
      replicas: 3
  dth:
    image: nileshkumar2343/paytm_dth:latest
    ports:
      - 63:80
    deploy:
      replicas: 3
  recharge:
    image: nileshkumar2343/paytm_recharge:latest
    ports:
      - 64:80
    deploy:
      replicas: 3
